stages:
  - build

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  services:
    - docker:dind

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/dev/dockerfile.dev -t kirillbad/bot-image:latest .

    - docker push kirillbad/bot-image:latest
