stages:
  - build
  - deploy

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/production/dockerfile -t kirillbad/anekdotarena:latest .

    - docker push kirillbad/anekdotarena:latest

deploy_to_stage:
  stage: deploy
  tags:
    - docker
    - python
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash scp; echo "apk RC: $?"
    - eval $(ssh-agent -s); echo "ssh-agent RC: $?"
    - chmod 600 "$SSH_PRIVATE_KEY_STAGE"; echo "chmod key RC: $?"
    - ssh-add "$SSH_PRIVATE_KEY_STAGE"; echo "ssh-add RC: $?"
    - mkdir -p ~/.ssh; echo "mkdir .ssh RC: $?"
    - chmod 700 ~/.ssh; echo "chmod .ssh RC: $?"
    - echo "Attempting ssh-keyscan for 100.67.76.27..."
    - ssh-keyscan -H "100.67.76.27" >> ~/.ssh/known_hosts; KEYS_RC=$?; echo "ssh-keyscan RC: $KEYS_RC" # Сохраняем код возврата
    - if [ $KEYS_RC -ne 0 ]; then echo "ssh-keyscan failed!"; exit 1; fi
    - echo "Checking known_hosts file..."
    - ls -la ~/.ssh/known_hosts; echo "ls known_hosts RC: $?"
    - echo "Contents of known_hosts:"
    - cat ~/.ssh/known_hosts; echo "cat known_hosts RC: $?"
    - chmod 644 ~/.ssh/known_hosts; echo "chmod known_hosts RC: $?"
    - echo "Attempting scp..."
    - scp "docker/production/docker-compose.yml" "kirillbad@100.67.76.27:docker-compose.yml"; echo "scp RC: $?"
  script:
    - ssh "kirillbad@100.67.76.27" "
      set -e; \
      docker compose up -d; "
