stages:
  - build
  - deploy

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/production/dockerfile -t kirillbad/anekdotarena:latest .

    - docker push kirillbad/anekdotarena:latest

deploy_to_stage:
  stage: deploy
  tags:
    - docker
    - python
  image: tailscale/tailscale:stable
  before_script:
    - tailscaled --state="mem:" --socket=/tmp/tailscaled.sock --tun=userspace-networking &
    - sleep 3
    - tailscale up --authkey=${TAILSCALE_AUTH_KEY} --hostname=${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA} --accept-routes --socket=/tmp/tailscaled.sock
    - tailscale status
  script:
    - ssh kirillbad@stage
      " set -e; \
      docker compose up -d; "
