stages:
  - build
  - deploy

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/production/dockerfile -t kirillbad/anekdotarena:latest .

    - docker push kirillbad/anekdotarena:latest

deploy_to_stage:
  stage: deploy
  tags:
    - docker
    - python
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - ssh-add "$SSH_PRIVATE_KEY_STAGE"
    - ssh-keyscan -H "stage" >> ~/.ssh/known_hosts
  script:
    - ssh "$STAGE_SERVER_USER_HOSTNAME" "
      set -e; \
      docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD; \
      cd ${STAGE_PROJECT_PATH:-/opt/anekdotarena-stage/}; \
      echo 'Pulling latest image for bot service...'; \
      docker-compose -f docker-compose.stage.yml pull bot; \
      echo 'Stopping and recreating bot service...'; \
      docker-compose -f docker-compose.stage.yml up -d --force-recreate bot; \
      echo 'Cleaning up unused Docker images on stage...'; \
      docker image prune -af; \
      docker logout"
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
