stages:
  - build
  - deploy

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/production/dockerfile -t kirillbad/anekdotarena:latest .

    - docker push kirillbad/anekdotarena:latest

deploy_to_stage:
  stage: deploy
  tags:
    - docker
    - python
  image: tailscale/tailscale:stable
  before_script:
    - apk add --no-cache openssh-client
    - tailscaled --state="mem:" &
    - tailscale up --auth-key=${TAILSCALE_AUTHKEY} --hostname="gitlab-$(cat /etc/hostname)" --accept-routes
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H stage >> ~/.ssh/known_hosts
  script:
    - scp "docker/production/docker-compose.yml" "kirillbad@stage:~/"
    - ssh kirillbad@stage "
      set -e \
      docker compose up -d"
