stages:
  - build
  - deploy

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/production/dockerfile -t kirillbad/anekdotarena:latest .

    - docker push kirillbad/anekdotarena:latest

deploy_to_stage:
  stage: deploy
  tags:
    - docker
    - python
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - chmod 600 "$SSH_PRIVATE_KEY_STAGE"
    - ssh-add "$SSH_PRIVATE_KEY_STAGE"
    - mkdir -p ~/.ssh
    - echo "Pinging 100.67.76.27 (ICMP might be blocked, but let's try)"
    - ping -c 3 100.67.76.27 || echo "Ping failed"
    - echo "Attempting TCP connection to 100.67.76.27 port 22 with netcat..."
    - nc -zv -w 3 100.67.76.27 22
    - ssh-keyscan -H "100.67.76.27" >> ~/.ssh/known_hosts
    - ls -la ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
    - scp "docker/production/docker-compose.yml" "kirillbad@100.67.76.27:docker-compose.yml"
  script:
    - ssh "kirillbad@100.67.76.27" "
      set -e; \
      docker compose up -d; "
