stages:
  - build
  - deploy

build_bot_image:
  stage: build

  tags:
    - docker
    - python

  image: docker:latest

  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

  script:
    - docker build -f docker/production/dockerfile -t kirillbad/anekdotarena:latest .

    - docker push kirillbad/anekdotarena:latest

deploy_to_stage:
  stage: deploy
  tags:
    - docker
    - python
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - ssh-add "$SSH_PRIVATE_KEY_STAGE"
    - chmod 600 "$SSH_PRIVATE_KEY_STAGE"
    - ssh-keyscan -H "stage" >> ~/.ssh/known_hosts
    - scp "docker/production/docker-compose.yml" "kirillbad@stage:anekdotarena/docker-compose.stage.yml"
  script:
    - ssh "$STAGE_SERVER_USER_HOSTNAME" "
      set -e; \
      docker compose up -d; \
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
