name: StartsJokes

services:
  bot:
    image: kirillbad/anekdotarena:latest
    container_name: bot-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: sh -c "python main.py"

  postgres:
    image: postgres:17.5-alpine
    container_name: postgres-container
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.0.1-alpine
    container_name: redis-container
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
